mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    RegistrationView,
    ProfileView,
    Base_ViewPriceLow,
    Base_ViewPriceH,
    Base_ViewPrice_Sale,
    BaseView_data_new,
    BaseView_data_old

)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('base_price_low/', Base_ViewPriceLow.as_view(), name='base_price_low'),
    path('base_price_h/', Base_ViewPriceH.as_view(), name='base_price_h'),
    path('base_data_new/', BaseView_data_new.as_view(), name='base_data_new'),
    path('base_data_old/', BaseView_data_old.as_view(), name='base_data_old'),
    path('base_sale/', Base_ViewPrice_Sale.as_view(), name='base_sale'),
    path('products/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('product-specs/', include('specs.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва категорії')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name='Категорія', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Найменування')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Зображення')
    code = models.CharField(max_length=234, verbose_name='Код продукту', blank=True)
    description = models.TextField(verbose_name='Опис', null=True, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=0, verbose_name='Стара ціна')
    sale = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Знижка', blank=True)
    size = models.CharField(max_length=255, verbose_name='Розмір')
    material = models.CharField(max_length=255, verbose_name='Матеріал', blank=True)
    color = models.CharField(max_length=255, verbose_name='Колір', blank=True)
    inside = models.CharField(max_length=255, verbose_name='Всередині', blank=True)
    sole = models.CharField(max_length=255, verbose_name='Підошва', blank=True)
    features = models.ManyToManyField("specs.ProductFeatures", blank=True, related_name='features_for_product')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

    def get_features(self):
        return {f.feature.feature_name: ' '.join([f.value, f.feature.unit or ""]) for f in self.features.all()}

    def get_sale(self): # Розрахувати вартість знижки
        price = int(self.price * (100 - self.sale) / 100)
        return price



class Image(models.Model):
    image = models.ImageField()
    product = models.ForeignKey(Product, default=None, related_name='images', on_delete=models.PROTECT)


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупець', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Загальна ціна')

    def __str__(self):
        return "Продукт: {} (для корзини)".format(self.product.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.get_sale()
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', null=True, verbose_name='Власник', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Загальна цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Користувач', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Замовлення покупця', related_name='related_order')

    def __str__(self):
        return "Покупець: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Нове замовлення'),
        (STATUS_IN_PROGRESS, 'Замовлення в обробці'),
        (STATUS_READY, 'Замовлення готове'),
        (STATUS_COMPLETED, 'Замовлення виконане')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Нова пошта'),
        (BUYING_TYPE_DELIVERY, 'Укрпошта')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупець', related_name='related_orders',
                                 on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Імя')
    last_name = models.CharField(max_length=255, verbose_name='Прізвище')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1424, verbose_name='Адрес доставки', null=True)
    num_vid = models.CharField(max_length=200, verbose_name='Номер відділення', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус замовлення',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Доставка',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Коментар до замовлення', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата створення замовлення')
    order_date = models.DateField(verbose_name='Дата отримки замовлення', default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Order

User = get_user_model()


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Бажана дата отримання замовлення'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'num_vid', 'buying_type', 'order_date', 'comment'
        )


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Користувач з логином "{username} не знайдений в системі')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Невірний пароль")
        return self.cleaned_data


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логін'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердіть пароль'
        self.fields['phone'].label = 'Номер телефону'
        self.fields['first_name'].label = 'Ім`я'
        self.fields['last_name'].label = 'Прізвище'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Електрона пошта'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['ru']:
            raise forms.ValidationError(
                f'Реєстрація для домена ".{domain}" неможлива'
            )
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                f'Даний поштовий адрес уже зареєстрований в системі'
            )
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                f'Ім`я "{username}" зайнято'
            )
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Паролі не співпадають')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'white')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="uk">
{% load static %}

</html>

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Ihor Bereznyi">

  <title>Shop Homepage - V__stelku</title>

  <!-- Bootstrap core CSS -->


  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'mainapp/css/main.css' %}">
   	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, maximum-scale=1">



	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand"  href="{% url 'base' %}">V__stelku</a>
      <a href="{% url 'base' %}"><img class="small-logo" src="{% static 'mainapp/img/favourite.png' %}" alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
            {% if not request.user.is_authenticated %}
          <li>
            <a class="text-maru" href="{% url 'login' %}">Авторизація</a>
          </li>
            <li>
            <a class="text-maru" href="{% url 'registration' %}">Реєстрація</a>
          </li>
          {% else %}
              <li class="nav-item">
                  <span class="text-maru">Раді Вас вітати, {% if request.user.is_authenticated %}<span class="badge badge-danger">
                    <a href="{% url 'profile' %}" style="text-decoration: none; font-size: 14px;">{{ request.user.username }}</a>
                  </span>{% else %} Гіcть!{% endif %}<a href="{% url 'logout' %}">|Вихід<i class="fas fa-arrow-alt-circle-right"></i></a></span>
              </li>
          {% endif %}
          </ul>
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}"><i class="fas fa-cart-arrow-down"></i>Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->


  {% block content %}
      <div class="title">
 <h1>V__stelku<br/>Ми Вас взуємо</h1>

</div>

  <div class="container">
    <div class="row">
      <div class="col-lg-3 mt-5">
        <div class="list-group">
          {% for category in categories %}
          <a href="{{ category.get_absolute_url }}" class="list-group-item"> <i class="fas fa-shoe-prints"></i>{{ category.name }}  ({{ category.product_set.count }})</a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

      <!-- /.col-lg-3 -->

          <span class="new_products">Фільтр:</span>
      <br>
      <span class="price_sort" >Ціна:
          <a href="{% url 'base_price_low' %}"><button  class="btn-confirm"><i class="fas fa-search-dollar"></i><i class="fas fa-sort-numeric-down"></i></button></a>
          <a href="{% url 'base_price_h' %}"><button class="btn-confirm"><i class="fas fa-search-dollar"></i><i class="fas fa-sort-numeric-up"></i></button></a>
      </span>

        <span class="price_sort" >Дата:
          <a href="{% url 'base_data_new' %}"><button  class="btn-confirm"><i class="fas fa-search-dollar"></i><i class="fas fa-sort-numeric-down"></i></button></a>
          <a href="{% url 'base_data_old' %}"><button class="btn-confirm"><i class="fas fa-search-dollar"></i><i class="fas fa-sort-numeric-up"></i></button></a>
      </span>

      <span class="price_sort" >Вигідні пропозиції:
           <a href="{% url 'base_sale' %}"><button class="btn-confirm"><i class="fas fa-gift"></i><i class="fas fa-percent"></i><i class="fas fa-user-tag"></i></button></a>
      </span>

      <div class="col-lg-9" >

        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
        {% endif %}

        <div class="row mt-5">
          {% for product in products %}
          <div class="col-lg-3   col-md-3 mb-3">
            <div class="card h-100">
              <a href="{{ reversed.product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <span class="text-decoration">{{ product.price }} <i class="fas fa-hryvnia"></i> </span>
                  <br>
                  <span class="new_price">{{ product.get_sale }} <i class="fas fa-hryvnia"></i></span> <span class="sale">-{{ product.sale }}<i class="fas fa-percentage"></i></span>
                <a href="{% url 'add_to_cart' slug=product.slug %}">
                  <button class="btn btn-danger">В корзину <i class="fas fa-cart-arrow-down"></i></button>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->
      {% endblock content %}
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
	<footer class="footer">
		<div class="container">
			<div class="footer-logo"><a></a></div>
            <ul class="social-link">
						<li class="email"><a href="mailto:bodnarchuchkam@gmail.com"><i class="fas fa-at"></i></a></li>
						<li class="telegram"><a href="https://t.me/vstelku"><i class="fab fa-telegram-plane"></i></a></li>
						<li class="phone"><a href="tel:+380989563397"><i class="fas fa-phone"></i></a></li>
						<li class="facebook"><a href="https://www.facebook.com/maria.bodnarchuk.980"><i class="fab fa-facebook-f"></i></a></li>
        				<li class="instagram"><a href="https://instagram.com/v__stelku?igshid=gx24zjif0m0q"><i class="fab fa-instagram"></i></a></li>

            </ul>
            <span class="copyright"><a href="{% url 'base' %}">V__stelku </a>&copy; <a1>Always better</a1></span>

  <!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
     <hr class="hr-shelf">
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
  <thead>
      <th class="hr-shelf" scope="col">Назва</th>
      <th class="hr-shelf" scope="col">Загальна сума</th>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr class="hr-shelf">
          <th  scope="row">{{ item.product.title }}
              <br>
              <img src="{{ item.product.image.url }}" class="img-cart">
              <br>
               Ціна:{{ item.product.get_sale }} <i class="fas fa-hryvnia"></i>
              <br>
                  <form action="{% url 'change_qty' slug=item.product.slug %}" method="POST">
              {% csrf_token %}
              <br>
                <input type="number" class="form-control" name="qty" style="width: 70px;" min="1" value="{{ item.qty }}">
                <input type="submit" class="btn btn-primary" value="Змінити кількіть">
            </form>
          </th>

            <td> {{ item.final_price }}<i class="fas fa-hryvnia"></i>
                <br>
                   <a href="{% url 'delete_from_cart' slug=item.product.slug %}"><button class="btn-del_cart">Видалити<i class="fas fa-trash-alt"></i></button></a>
                <br>

          </td>
        </tr>

    {% endfor %}
        <tr>
          <td>Разом: <strong>{{ cart.final_price }} <i class="fas fa-hryvnia"></i></strong></td>
          <td> <a href="{% url 'checkout' %}"><button class="btn btn-pr">Перейти до оформлення</button></a>
          </td>
        </tr>
  </tbody>
</table>
{% endif %}
{% endblock content %}

mainapp/templates/category_detail.html
{% extends 'base.html' %}
{% load search_filter %}
{% load static %}

{#    <form action="{% url 'category_detail' slug=category.slug %}" method="GET">#}
{#        {{ category|product_spec }}#}
{#    <p class="text-center">#}
{#        <button class="btn btn-outline-success" type="submit">Пошук</button>#}
{#        <button class="btn btn-outline-info" type="submit">Очистити</button>#}
{#    </p>#}
{#    </form>#}

{% block content %}

{% block productfilter %}
      <form class="d-flex mt-3" action="{% url 'category_detail' slug=category.slug %}" method="GET">
        <input class="form-row" name="search" type="search" placeholder="Пошук товара" aria-label="Search">
        <button class="btn btn-confirm" type="submit">Пошук</button>
      </form>
        <hr>
{% endblock productfilter %}

    <nav aria-label="breadcrumb" class="mt-5">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Головна</a></li>
        <li class="breadcrumb-item active">{{ category.name }}</li>
      </ol>
    </nav>
<div class="row">

  {% for product in category_products %}
  <div class="col-lg-3   col-md-3 mb-3">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <span class="text-decoration">{{ product.price }} <i class="fas fa-hryvnia"></i> </span>
                  <br>
                  <span class="new_price">{{ product.get_sale }} <i class="fas fa-hryvnia"></i></span> <span class="sale">-{{ product.sale }}<i class="fas fa-percentage"></i></span>
                <a href="{% url 'add_to_cart' slug=product.slug %}">
                  <button class="btn btn-danger">В корзину <i class="fas fa-cart-arrow-down"></i></button>
                </a>
              </div>
            </div>
          </div>
  {% endfor %}
</div>

{% endblock content %}

mainapp/templates/profile.html
{% extends 'base.html'%}
{% block content %}
{% load static %}
<h3 class="mt-3 mb-3">Замовлення користувача {{ request.user.username}}</h3>
{% if not orders.count %}
<div class="col-md-12" style="margin-top: 300px; margin-bottom: 300px;">
    <h3>У Вас ще немає замовлень. <a href="{% url 'base' %}">Почитайте робити покупки</a></h3>
</div>
{% else %}
<div class="col-md-12" style="margin-bottom: 250px; margin-top: 250px;">
<table class="table">
    <thead>
          <th scope="col">Номер</th>
          <th scope="col">Статус</th>
          <th scope="col">Сума</th>
          <th scope="col">Товар</th>
          <th scope="col">Додатково</th>
    </thead>
    <tbody>
         {% for order in orders %}
            <tr>
                <th scope="row">{{order.id}}</th>
                <td>{{order.get_status_display}}</td>
                <td>{{order.cart.final_price}}<i class="fas fa-hryvnia"></i></td>
                <td>
                     <ul>
                         {% for item in order.cart.products.all %}
                            <li>{{ item.product.title }}&times;{{item.qty}}</li>
                         {% endfor %}
                     </ul>
                </td>
             <td>
                 <button class="btn btn-info" data-toggle="modal" data-target="#exampleModal-{{ order.id }}">Додатково</button>
                  <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Деталі замовлення</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h4 class="text-center">Товар</h4>
          <table class="table">
              <thead>
                <tr>
                    <th scope="col">Назва</th>
                    <th scope="col">Зображення</th>
                    <th scope="col">Ціна</th>
                    <th scope="col">Кількість</th>
                    <th scope="col">Загальна сума</th>
                </tr>
              </thead>
              <tbody>
              {% for item in order.cart.products.all %}
                  <tr>
                      <th scope="row">{{ item.product.title }}</th>
                      <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
                      <td><strong>{{item.product.price }}</strong> <i class="fas fa-hryvnia"></i></td>
                      <td>{{ item.qty }}</td>
                      <td>{{ item.final.price }} <i class="fas fa-hryvnia"></i></td>
                  </tr>
              {% endfor %}
                   <tr>
                       <td colspan="2"></td>
                       <td>Разом:</td>
                       <td> {{order.cart.total_products}} </td>
                       <td><strong>{{ order.cart.final_price }}</strong><i class="fas fa-hryvnia"></i></td>
                   </tr>
              </tbody>
          </table>
          <hr>
          <h4 class="text-center">Додаткова інформація</h4>
          <p>Ім'я: <strong>{{ order.first_name }}</strong></p>
          <p>Прізвище: <strong>{{ order.last_name }}</strong></p>
          <p>Телефон: <strong>{{ order.customer.phone }}</strong></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
      </div>
    </div>
  </div>
</div>
             </td>
            </tr>
         {% endfor %}
    </tbody>
</table>
</div>

{% endif %}
{% endblock %}